### ISSUE TITLE
This Problem is coming!

### ISSUE THREAD

**Issue by Craftboy98** [ARVIN3108/ArvinCord#1]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\varah\OneDrive\Desktop\bungee\compiled\ArvinCord\ArvinCord-Proxy of C:\Users\varah\OneDrive\Desktop\bungee\compiled\ArvinCord\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\varah\OneDrive\Desktop\bungee\compiled\ArvinCord\ArvinCord-Proxy of C:\Users\varah\OneDrive\Desktop\bungee\compiled\ArvinCord\pom.xml does not exist @

So is this a problem of pom.xml?

**Comment by ARVIN3108** [comment]
Did you compile it with command `/arvincord b` ? And I recommend running it using git-bash

**Comment by Craftboy98** [comment]
> Did you compile it with command `/arvincord b` ? And I recommend running it using git-bash
i used it with git bash but it dint worked so i did mvn package

**Comment by Craftboy98** [comment]
wait nvm i got the problem if that will work thanks! for helping cuz i think i didnt used `/arvincord b`

**Comment by Craftboy98** [comment]
and do you have a discord account cuz if i get any problemi can dm you!

**Comment by ARVIN3108** [comment]
You're welcome i will add my discord on readme later
