### ISSUE TITLE
ITS STIL SAME!

### ISSUE THREAD

**Issue by Craftboy98** [ARVIN3108/ArvinCord#2]
incord (master)
$ ./arvincord b
fatal: destination path 'C:/Users/varah/OneDrive/Desktop/bungee/compiled/ArvinCord/FlameCord' already exists and is not an empty directory.
fatal: clone of 'https://github.com/2lstudios-mc/FlameCord' into submodule path 'C:/Users/varah/OneDrive/Desktop/bungee/compiled/ArvinCord/FlameCord' failed
Failed to clone 'FlameCord'. Retry scheduled
fatal: destination path 'C:/Users/varah/OneDrive/Desktop/bungee/compiled/ArvinCord/FlameCord' already exists and is not an empty directory.
fatal: clone of 'https://github.com/2lstudios-mc/FlameCord' into submodule path 'C:/Users/varah/OneDrive/Desktop/bungee/compiled/ArvinCord/FlameCord' failed
Failed to clone 'FlameCord' a second time, aborting
scripts/build.sh: line 5: pushd: ArvinCord-Proxy: No such file or directory
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module C:\Users\varah\OneDrive\Desktop\bungee\compiled\arvincord\ArvinCord-Proxy of C:\Users\varah\OneDrive\Desktop\bungee\compiled\arvincord\pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.github.waterfallmc:waterfall-super:dev-SNAPSHOT (C:\Users\varah\OneDrive\Desktop\bungee\compiled\arvincord\pom.xml) has 1 error
[ERROR]     Child module C:\Users\varah\OneDrive\Desktop\bungee\compiled\arvincord\ArvinCord-Proxy of C:\Users\varah\OneDrive\Desktop\bungee\compiled\arvincord\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by ARVIN3108** [comment]
Can you delete the directory named `FlameCord`?
